server:
  port: 9192

spring:
  application:
    name: CART-SERVICE
  data:
    mongodb:
      uri: mongodb://localhost:27017/cart_service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultzone: http://localhost:8761/eureka/
  instance:
    hostname: localhost